### ISSUE TITLE
Ideas for initial lint rules

### ISSUE THREAD

**Issue by keithamus** [github/eslint-plugin-custom-elements#3]
- [x] Define Tag After Class Definition #4
 - [x] Expose Class on Global #5
 - [x] Extends Correct Class #9
 - [x] File Name Matches Element #6 
 - [x] No Constructor #7 
 - [x] No Customized Built in Elements #13
 - [x] No DOM Traversal in Connectedcallback/AttributeChangedCallback #8, #40
 - [x] No Exports with Element #16 
 - [ ] No Method Name Shadowing
 - [x] No on Prefixed Method #24
 - [ ] No Parent Traversal
 - [ ] No Public Instance Field
 - [x] No Unchecked Define #28 
 - [x] One Element Per File #11
 - [x] Tag Name Matches Class #15
 - [x] Valid Tag Name #10

**Comment by keithamus** [comment]
This project has now been merged with [eslint-plugin-wc](https://github.com/43081j/eslint-plugin-wc). Please head there for updates and maintenance.
